# Site settings
title: Justin Hernandez
description: >
  A simple blog about whatever I am learning

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jmarthernandez.github.io" # the base hostname
author:
  fullname: Justin
  github: jmarthernandez
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown